### ISSUE TITLE
Fails to build from AUR

### ISSUE THREAD

**Issue by Prayag2** [luisbocanegra/kde-material-you-colors#10]
I was trying to install it from the AUR but got the following error:
```
running egg_info
writing Colr.egg-info/PKG-INFO
Traceback (most recent call last):
  File "/home/prayag/.cache/yay/python-colr/src/Colr-0.9.1/setup.py", line 50, in <module>
    setup(
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.10/site-packages/setuptools/command/install.py", line 68, in run
    return orig.install.run(self)
  File "/usr/lib/python3.10/distutils/command/install.py", line 580, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.10/site-packages/setuptools/command/install_egg_info.py", line 34, in run
    self.run_command('egg_info')
  File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 292, in run
    writer(self, ep.name, os.path.join(self.egg_info, ep.name))
  File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 656, in write_pkg_info
    metadata.write_pkg_info(cmd.egg_info)
  File "/usr/lib/python3.10/distutils/dist.py", line 1117, in write_pkg_info
    self.write_pkg_file(pkg_info)
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 167, in write_pkg_file
    write_field('Summary', single_line(self.get_description()))
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 151, in single_line
    raise ValueError('Newlines are not allowed')
ValueError: Newlines are not allowed
==> ERROR: A failure occurred in package().
    Aborting...
 -> error making: python-colr
```

It seems like it's facing some issues installing `python-colr` package. I have reported this in the python-colr AUR page too (https://aur.archlinux.org/packages/python-colr#comment-860172).

**Comment by Kuchenmampfer** [comment]
I have found a workaround until this is fixed:
- 0st
git clone `python-colr` and `kde-material-you-colors`
- 1st
go to the `python-colr` folder and run `makepkg -o`
o: no build, it will run till prepare () included but not build ()
- 2nd
Open the `setup.py` file that throws the error and add `.strip('\n')` at the end of both lines that end with `f.read()`
This removes all the newline characters from the descriptions that could cause the error
- 3rd
run `makepkg -sei`
s: install dependencies
e: no extract
i: install with pacman
- 4th
go to the `kde-material-you-colors` folder and run `makepkg -i`

**Comment by luisbocanegra** [comment]
Yeah, there is an open pull request in [Colr repo](https://github.com/welbornprod/colr) see [https://github.com/welbornprod/colr/pull/10](https://github.com/welbornprod/colr/pull/10) that seems fixes this problem.

Which is weird it that _It works on my system™_

**Comment by Kuchenmampfer** [comment]
Maybe you do not have the latest setuptools? Idk...

**Comment by luisbocanegra** [comment]
Yeah that is! I have the setuptools v59 installed from official packages and has been flagged out-of-date since 2022-03-21 while setuptools from pip is now on v62. Maybe you have installed it with pip as root before or are using the git version of it?

**Comment by luisbocanegra** [comment]
Should be fixed in: [v0.2.0BETA](https://github.com/luisbocanegra/kde-material-you-colors/releases/tag/v0.2.0BETA), (Colr module is still broken but is now an optional dependency) **not yet un AUR** please test:
```sh
mkdir kde-material-you-colors
cd kde-material-you-colors
curl https://raw.githubusercontent.com/luisbocanegra/kde-material-you-colors/testing/PKGBUILD -o PKGBUILD
makepkg -si
```

**Comment by SpxterWohlf** [comment]
I had the same issue, #24 seemed to work 😁

**Comment by luisbocanegra** [comment]
Thanks, just one more https://github.com/luisbocanegra/kde-material-you-colors/issues/11 and will push to AUR if all is good.
