### ISSUE TITLE
SkiaSharp dependency is incompatible and 81.3 must be used

### ISSUE THREAD

**Issue by SpxterWohlf** [luisbocanegra/kde-material-you-colors#2]
Updating to the latest SkiaSharp fixed the issue

```
Current config: Plugin: org.kde.image | Light mode: None | File: None | Monitor: 0
Settting color schemes for /home/spectator/Pictures/assets/wallpapers/shadeofpalmgrove-2.png
Unhandled exception. System.TypeInitializationException: The type initializer for 'SkiaSharp.SKData' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'SkiaSharp.SKObject' threw an exception.
 ---> System.InvalidOperationException: The version of the native libSkiaSharp library (80.2) is incompatible with this version of SkiaSharp. Supported versions of the native libSkiaSharp library are in the range [80.3, 81.0).
   at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Version minSupported, Version current, Boolean throwIfIncompatible)
   at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Boolean throwIfIncompatible)
   at SkiaSharp.SKObject..cctor()
   --- End of inner exception stack trace ---
   at SkiaSharp.SKData..cctor()
   --- End of inner exception stack trace ---
   at SkiaSharp.SKData.Create(Stream stream)
   at SkiaSharp.SKImage.FromEncodedData(Stream data)
   at Program.Main(String[] args)
Error trying to get colors from "/home/spectator/Pictures/assets/wallpapers/shadeofpalmgrove-2.png"
^CTraceback (most recent call last):
  File "/usr/lib/kde-material-you-colors/kde-material-you-colors.py", line 248, in <module>
```

**Comment by SpxterWohlf** [comment]
This is strange, even after I refreshed mirrors and everything it still kept trying to install 80.2 even though the latest for arch is 81.3 which is what it's set to use. Im gonna close this because it must've been a me issue.
