### ISSUE TITLE
Titlebars and other elements are barely tinted in v1.9.1

### ISSUE THREAD

**Issue by Loklann** [luisbocanegra/kde-material-you-colors#208]
**Describe the bug**
Just updated from 1.8.0 to 1.9.1 through `pip`, and noticed a very big difference in the colour amount on some UI elements, most noticeably the titlebars. They are much less tinted than before, resulting in a less colourful style. No settings seem to affect this (not even the different palette combinations), only bumping up the Colourfulness can make a difference, but they still remain heavily under-tinted compared to some other elements. In most cases, it also seems like the window's colours is barely tinted (see screenshots for comparison).

**To Reproduce**
Steps to reproduce the behaviour:
Install and use v1.9.1 , use with Klassy or Breeze (Window Decorations + Application Style in both cases).

**Expected behavior**
Windows should be properly tinted with the colour palette extracted from wallpaper, as per the Material-You Design Guidelines (like what v1.8.0 achieved perfectly) .

**Screenshots**
1. Dolphin on Klassy (Application Style + Window Decorations) and kde-material-you-colors v1.8.0
![Screenshot_20240522_182159](https://github.com/luisbocanegra/kde-material-you-colors/assets/100464654/3062a4b4-39c2-4ce0-ac4c-0741c09dfeb3)
2. Dolphin on Klassy (Application Style + Window Decorations) and kde-material-you-colors v1.9.1
![Screenshot_20240522_182349](https://github.com/luisbocanegra/kde-material-you-colors/assets/100464654/81f9ff51-0901-420c-a038-f7d379ec155e)

**Desktop (please complete the following information):**
 - Operating System: Fedora 40
 - KDE Plasma Version: 6.0.4
 - KDE Frameworks Version: 6.2.0
 - Qt Version: 6.7.0
 - Graphics Platform: Wayland
 - Things in your system that might be relevant :N/A

**Additional context**
Same problem on my Arch Linux VM (installed throught the AUR via `yay`).
Here's some logs from running `kde-material-you-colors` (v1.9.1 ; Fedora 40) in Konsole (probably not relevant, but hey), this doesn't show up in my Arch VM  : 
```
[E] konsole_utils: reload_profile: [Errno 2] No such file or directory: 'qdbus6'
Traceback (most recent call last):
  File "/home/lachlancraig/.local/share/pipx/venvs/kde-material-you-colors/lib64/python3.12/site-packages/kde_material_you_colors/utils/konsole_utils.py", line 184, in reload_profile
    result = subprocess.run(
             ^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'qdbus6'
```

**Comment by luisbocanegra** [comment]
In 1.8.0 I was using a version of material you library that didn't have [surface color variants](https://m3.material.io/styles/color/roles#89f972b1-e372-494c-aabc-69aea34ed591), which are used to define the level of emphasis of the UI. So what I ended doing was to blend the background against the accent color based purely in my own criteria.

On 1.9.0 I removed most of these colors (pywal/konsole text which is still modified to have good contrast) and replaced the elements that used them with the surface variants I felt matched the better.

The downside is that yes they are a lot less colorful, but can definitely be improved, after all we aren't forced to stick exactly to Material You guidelines, specially because it's not possible to make a 1:1 copy due to the Plasma colorscheme limitations and the fact that desktop applications have a lot more things on screen than the average Android/Web app.

![image](https://github.com/luisbocanegra/kde-material-you-colors/assets/15076387/354286d7-f658-46df-8acd-7949f112ef39)

![Screenshot_20240522_130024](https://github.com/luisbocanegra/kde-material-you-colors/assets/15076387/672276c0-ee6e-4fa7-88ef-cce9a743fcf5)

![Screenshot_20240522_130132](https://github.com/luisbocanegra/kde-material-you-colors/assets/15076387/8e3ceab6-2263-4f9a-b427-902a2ada1776)

**Comment by Loklann** [comment]
I see, this decision 100% makes sense and I can definitely see the colours are more coherent / cohesive overall. Perhaps yet another setting could be added, this time controlling the overall level of tint in the whole colour scheme.
ex: if some element is 15% tinted and another 25% tinted, you could add a slider and bump the tint level of the entire colour scheme by 15%, bringing those two elements to (respectively, 30% and 40%). You could also explicit ratios of tint for each element in the colour scheme, which would remain identical even if the overall tint level was changed (if you don't push it to extremes). Or even, since I see you can control the Klassy titlebar opacity, control its tint level ? And last suggestion, maybe just provide the older (and less accurate) backend in newer packages as a toggle ?
For me, the most striking example is the almost complete lack of color in the Dolphin sidebar in the 2nd screenshot I posted, it looks closer to the original Breeze colour scheme since it's really under-tinted.
Anyway, your work is very impressive, and I'll try to see what things I can bring to it once I've got more time to get through your code.

**Comment by luisbocanegra** [comment]
Changed the header surface variant and with colorfulness all the way up this is the result.

![header_surfaceContainer](https://github.com/luisbocanegra/kde-material-you-colors/assets/15076387/80519662-8201-40cb-99bb-74c8f9c70933)
![Screenshot_20240620_194929](https://github.com/luisbocanegra/kde-material-you-colors/assets/15076387/86bb0e3a-3dd3-4a01-9f23-42eeead9d030)

**Comment by Loklann** [comment]
Looks great! 
It seems to also remove incoherences like this, where there is no transition/ no link between colors with certain window border styles/thicknesses : 
![Screenshot_20240622_201529](https://github.com/luisbocanegra/kde-material-you-colors/assets/100464654/168c645e-97c1-4fdb-b0f0-aea1c1d62570)

Although, I also notice you've removed the tint for text and icons ? 

1.9.1 :
![Screenshot_20240622_202053](https://github.com/luisbocanegra/kde-material-you-colors/assets/100464654/b4695c47-6888-42a4-b51c-e5eafaf2220f)

1.9.3 :
![Screenshot_20240622_202139](https://github.com/luisbocanegra/kde-material-you-colors/assets/100464654/608edffd-9856-41c3-869d-cc06b958e5d3)


I thought tinting those was a good idea and made everything come together, although it's not accurate to MD3.

**Comment by luisbocanegra** [comment]
> Although, I also notice you've removed the tint for text and icons ?
> 
> 1.9.1 : ![Screenshot_20240622_202053](https://private-user-images.githubusercontent.com/100464654/341990350-b4695c47-6888-42a4-b51c-e5eafaf2220f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwODQxNjksIm5iZiI6MTcxOTA4Mzg2OSwicGF0aCI6Ii8xMDA0NjQ2NTQvMzQxOTkwMzUwLWI0Njk1YzQ3LTY4ODgtNDJhNC1iNTFjLWU1ZWFmYWYyMjIwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMlQxOTE3NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMTg3MDYyNDM2MzE2ODQ1Yjc4ZjAwMGRiZTI2YTJlY2ExYjQ4ZWU1M2RhNTFlMWNmYzExY2RiYzVkZjQ1ZWFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wIGlmYbV8ySBpn98N3324nXZzPjM2bw9X6Ulb7r_GAg)
> 
> 1.9.3 : ![Screenshot_20240622_202139](https://private-user-images.githubusercontent.com/100464654/341990359-608edffd-9856-41c3-869d-cc06b958e5d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwODQxNjksIm5iZiI6MTcxOTA4Mzg2OSwicGF0aCI6Ii8xMDA0NjQ2NTQvMzQxOTkwMzU5LTYwOGVkZmZkLTk4NTYtNDFjMy04NjlkLWNjMDZiOTU4ZTVkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMlQxOTE3NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NDNjOGEwNTY5ZjZhODRlY2M5YWY5NDk2YjNkMTFkZjZjYzQ3ZTNiZWVhZmYzYzQxYWU0NjhjMGY4ZDQ3YjVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3_DQWTBsskHYDM2Ss7MtGkj1O8thxsrA9oly5hLg6MY)
> 
> I thought tinting those was a good idea and made everything come together, although it's not accurate to MD3.

I also like it, will bring it back as an extra checkbox under colorfulness

**Comment by Loklann** [comment]
> 
> I also like it, will bring it back as an extra checkbox under colorfulness

Great!
Also, I wonder, do you have alpha-transparency control over the colors generatd ?

**Comment by luisbocanegra** [comment]
Currently the generated colors are converted from RGBA to hexadecimal format (RGB). On the places where transparency is applied I either make use of alpha property or add alpha channel to these colors. It's a mess because it's been like this basically since I started it and didn't bother me enough to change it.
I have thought of switching all my color logic to RGBA, make use of it to generate schemes with alpha (where possible) and probably keep storing the output json in hex RGB

**Comment by Loklann** [comment]
> Currently the generated colors are converted from RGBA to hexadecimal format (RGB). On the places where transparency is applied I either make use of alpha property or add alpha channel to these colors. It's a mess because it's been like this basically since I started it and didn't bother me enough to change it. I have thought of switching all my color logic to RGBA, make use of it to generate schemes with alpha (where possible) and probably keep storing the output json in hex RGB. But haven't had the time/motivation to do that as I am pretty sure will require a substantial cleanup/rewrite.

I see, I just thought about transparency because it could do for a cool effect along with the Force Blur kwin effect. Imagine Qt Apps following the MY Breeze colour scheme (like Dolphin), with the same transparency as the panel : it would create some good looking coherency I think. Of course, the amount of work you say this would require is absolutely not justifiable just for this.

**Comment by luisbocanegra** [comment]
> I thought tinting those was a good idea and made everything come together, although it's not accurate to MD3.

Brought that back in an unrelated commit [`1af8bfc` (#225)](https://github.com/luisbocanegra/kde-material-you-colors/pull/225/commits/1af8bfc3e40b32fce0afd5e9c4d4187e7d0218bd#diff-9f21db7d45fa39aad6efa6be27839a608e8ff98dc4fa4a51eed1826c8db5a678) 😅

Opened a separate issue for transparency in case some day I clean the mess and decide to work on that https://github.com/luisbocanegra/kde-material-you-colors/issues/246
