### ISSUE TITLE
 Screenshot Helper not working

### ISSUE THREAD

**Issue by Loklann** [luisbocanegra/kde-material-you-colors#211]
**Describe the bug**

The Screenshot Helper doesn't work : no color change on wallaper change with different wallpaper plugins.
The "Use only Screenshot Mode" option, when activated and using the "Image" wallpaper plugin, shows that the Screenshot Helper is not working : no change is noticed.

**To Reproduce**

Install kde-material-you-colors and the screenshot helper, and switch to a different wallpaper plugin than "Image". 

**Expected behavior**

The Screenshot Helper should  work and dynamically change the colors.

**Screenshots**

N/A

**Desktop (please complete the following information):**

 - Operating System: Fedora 40 KDE
 - KDE Plasma Version: 6.0.5
 - KDE Frameworks Version: 6.3.0
 - Qt Version: 6.7.1
 - Graphics Platform: Wayland
 - Things in your system that might be relevant: N/A

**Additional context**

The installation seems to complete correctly : 
```
-- The C compiler identification is GNU 14.1.1
-- The CXX compiler identification is GNU 14.1.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Found WrapAtomic: TRUE  
-- Found OpenGL: /usr/lib64/libOpenGL.so   
-- Found WrapOpenGL: TRUE  
-- Found XKB: /usr/lib64/libxkbcommon.so (found suitable version "1.6.0", minimum required is "0.5.0") 
-- Found WrapVulkanHeaders: /usr/include  
Installing in /home/lachlancraig/.local. Run /home/lachlancraig/kde-material-you-colors/build/src/screenshot_helper/prefix.sh to set the environment for kde-material-you-colors.
Plugin Id: luisbocanegra.kdematerialyou.colors
Version: 0.4.1
-- Configuring done (0.8s)
-- Generating done (0.0s)
-- Build files have been written to: /home/lachlancraig/kde-material-you-colors/build
[  0%] Built target kde-material-you-colors-screenshot-helper_autogen_timestamp_deps
[ 20%] Automatic MOC and UIC for target kde-material-you-colors-screenshot-helper
[ 20%] Built target kde-material-you-colors-screenshot-helper_autogen
[ 40%] Building CXX object src/screenshot_helper/CMakeFiles/kde-material-you-colors-screenshot-helper.dir/kde-material-you-colors-screenshot-helper_autogen/mocs_compilation.cpp.o
[ 60%] Building CXX object src/screenshot_helper/CMakeFiles/kde-material-you-colors-screenshot-helper.dir/main.cpp.o
[ 80%] Linking CXX executable ../../bin/kde-material-you-colors-screenshot-helper
[100%] Built target kde-material-you-colors-screenshot-helper
-- Install configuration: ""
-- Installing: /home/lachlancraig/.local/share/applications/kde-material-you-colors-screenshot-helper.desktop
-- Installing: /home/lachlancraig/.local/bin/kde-material-you-colors-screenshot-helper
-- Set non-toolchain portion of runtime path of "/home/lachlancraig/.local/bin/kde-material-you-colors-screenshot-helper" to "/home/lachlancraig/.local/lib64"
```
and the screenshot-helper script is in $HOME/.local/bin : 

```
$ cd $HOME/.local/bin && ls -a
.  ..  kde-material-you-colors  kde-material-you-colors-screenshot-helper  pylsp
```
yet I don't quite get what  this is supposed to do :

`
-- Set non-toolchain portion of runtime path of "/home/lachlancraig/.local/bin/kde-material-you-colors-screenshot-helper" to "/home/lachlancraig/.local/lib64"`

since this directory doesn't exist on my install : 

```
$ cd $HOME/.local && ls
bin  lib  share  state
```

**Noticed errors during installation** 

The instructions provided in the README : 
```
git clone https://github.com/luisbocanegra/kde-material-you-colors
./install-screenshot-helper.sh
```
cause this : 
```
bash: ./install-screenshot-helper.sh: No such file or directory

```

therefore the instructions should become : 
```
git clone https://github.com/luisbocanegra/kde-material-you-colors
cd kde-material-you-colors
./install-screenshot-helper.sh
```

**Comment by luisbocanegra** [comment]
Hi, I think there is a problem with the helper not having permission to take screenshots. What's the output of `kde-material-you-colors`?

**Comment by luisbocanegra** [comment]
> ```
> $ cd $HOME/.local/bin && ls -a
> .  ..  kde-material-you-colors  kde-material-you-colors-screenshot-helper  pylsp
> ```
> 
> yet I don't quite get what this is supposed to do :
> 
> ` -- Set non-toolchain portion of runtime path of "/home/lachlancraig/.local/bin/kde-material-you-colors-screenshot-helper" to "/home/lachlancraig/.local/lib64"`
> 
> since this directory doesn't exist on my install :
> 
> ```
> $ cd $HOME/.local && ls
> bin  lib  share  state
> ```

Neither does on mine but it should work without that.

> 
> **Noticed errors during installation**
> 
> The instructions provided in the README :
> 
> ```
> git clone https://github.com/luisbocanegra/kde-material-you-colors
> ./install-screenshot-helper.sh
> ```
> 
> cause this :
> 
> ```
> bash: ./install-screenshot-helper.sh: No such file or directory
> ```
> 
> therefore the instructions should become :
> 
> ```
> git clone https://github.com/luisbocanegra/kde-material-you-colors
> cd kde-material-you-colors
> ./install-screenshot-helper.sh
> ```

Thanks for the observation

**Comment by Loklann** [comment]
> Hi, I think there is a problem with the helper not having permission to take screenshots. What's the output of `kde-material-you-colors`?

Hi, that could be it, here is the output :

```
[D] utils: kill_existing: Found previous process in PID file: '2614' killing...
[I] main: main: ###### STARTED NEW SESSION ######
[D] main: main: Installed in /home/lachlancraig/.local/share/pipx/venvs/kde-material-you-colors/lib64/python3.12/site-packages/kde_material_you_colors
[D] config: eval_conf: Config "iconslight": empty, using fallback: None
[D] config: eval_conf: Config "iconsdark": empty, using fallback: None
[D] config: eval_conf: Config "on_change_hook": empty, using fallback: None
[D] config: eval_conf: Config "color": empty, using fallback: None
[D] config: eval_conf: Config "custom_colors_list": empty, using fallback: None
[D] config: eval_conf: Config "darker_window_list": empty, using fallback: None
[D] config: eval_conf: Config "qdbus_executable": empty, using fallback: None
[D] main: main: {'light': True, 'file': None, 'monitor': 0, 'ncolor': 0, 'iconslight': None, 'iconsdark': None, 'pywal': True, 'pywal_light': True, 'light_blend_multiplier': 1.0, 'dark_blend_multiplier': 1.0, 'on_change_hook': None, 'sierra_breeze_buttons_color': False, 'disable_konsole': False, 'titlebar_opacity': 100, 'titlebar_opacity_dark': 100, 'toolbar_opacity': 100, 'toolbar_opacity_dark': 100, 'konsole_opacity': 100, 'konsole_opacity_dark': 100, 'color': None, 'klassy_windeco_outline': False, 'custom_colors_list': None, 'darker_window_list': None, 'use_startup_delay': False, 'startup_delay': 0, 'plasma_follows_scheme': False, 'pywal_follows_scheme': False, 'main_loop_delay': 1.0, 'screenshot_delay': 10.0, 'once_after_change': False, 'pause_mode': False, 'screenshot_only_mode': False, 'scheme_variant': 0, 'chroma_multiplier': 10.0, 'tone_multiplier': 1.0, 'qdbus_executable': None}
[I] main: main: Wallpaper: org.kde.image (image): /home/lachlancraig/MEGA/MyPictures/Wallpapers/Firewatch/FirewatchBlueSkyThorofareLookout.png
[E] apply_themes: apply: QDbus executable 'qdbus6' wasn't found, there will be errors. Please set the correct one in the configuration
[I] m3_scheme_utils: get_color_schemes: Best colors: 0:#3998eb 1:#b6e4ea 2:#70ccf2 3:#7070c0 4:#92827c 5:#605b61 6:#9a8d8c
[I] m3_scheme_utils: get_color_schemes: Using seed: 0:#3998eb
[I] plasma_utils: apply_color_schemes: Successfully applied the colour scheme MaterialYouLight to your current Plasma session
[D] plasma_utils: set_icons: No icon theme specified.
[I] konsole_utils: get_default_profile: Found default profile 'Profile 1.profile'
[D] konsole_utils: reload_profile: Konsole services (windows) running (1):
[E] konsole_utils: reload_profile: [Errno 2] No such file or directory: 'qdbus6'
Traceback (most recent call last):
  File "/home/lachlancraig/.local/share/pipx/venvs/kde-material-you-colors/lib64/python3.12/site-packages/kde_material_you_colors/utils/konsole_utils.py", line 184, in reload_profile
    result = subprocess.run(
             ^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'qdbus6'
[W] pywal_utils: apply_schemes: Pywal option enabled but python module is not installed, ignored
[I] kwin_utils: reload: Reloading KWin
 #f8f9ff  #1e4fd0  #ca4f41  #b150d0  #417fc7  #c85d43  #4c9bcb  #54b4c7 
 #465f79  #1943b0  #aa4439  #9544b0  #376ba9  #a84f3b  #4083ac  #4798a9 
 #5a7089  #5e89eb  #e6887c  #d08ae9  #7ca9e2  #e3917e  #87bee4  #8fd1e0 
```

**Comment by luisbocanegra** [comment]
According to that log you have disabled `screenshot_only_mode`:

```
'screenshot_only_mode': False,
```

Also there is an error about qdbus which is needed to get the desktop window id, please change it to the correct name your distribution uses it think is `qdbus-qt6`

**Comment by Loklann** [comment]
> According to that log you have disabled `screenshot_only_mode`:
> 
> ```
> 'screenshot_only_mode': False,
> ```
> 
> Also there is an error about qdbus which is needed to get the desktop window id, please change it to the correct name your distribution uses it think is `qdbus-qt6`

Ah yes, thanks, the qdbus exec not being specified was indeed the issue !
