### ISSUE TITLE
Pywal cache not updated

### ISSUE THREAD

**Issue by areyoufeelingitnowmrkrebs** [luisbocanegra/kde-material-you-colors#237]
**Describe the bug**
The files in ~/.cache/wal are not being updated except for ~/.cache/wal/sequences.

**To Reproduce**
1. Navigate to ~/.cache/wal and delete everything
2. Start kde-material-you-colors
3. Set a wallpaper
4. Run `ls -a ~/.cache/wal/`
5. See that it is still empty
6. Run `wal -i <image file path>`
7. Run `ls -a ~/.cache/wal`
8. See that it has been repopulated

**Expected behavior**
The files in ~/.cache/wal should be generated whenever pywal is ran.

**Desktop (please complete the following information):**
 - Operating System: Arch Linux
 - KDE Plasma Version: 6.2.4
 - Qt Version: 5.15.16
 - Graphics Platform: x11
 - Things in your system that might be relevant: I am calling kde-material-you-colors from a login script in KDE Plasma, here are the contents of the login and logout scripts.
 
 ```
$ cat .config/kde-material-you-colors/start
#!/bin/bash
kde-material-you-colors -wal &
exit
```

```
$ cat .config/kde-material-you-colors/stop
#!/bin/bash
kde-material-you-colors --stop
```

**Comment by luisbocanegra** [comment]
If I delete the folder it is correctly created for me after running `kde-material-you-colors -wal` can you share the output of that command please

**Comment by areyoufeelingitnowmrkrebs** [comment]
> If I delete the folder `~/.cache/wal` it is correctly created after running `kde-material-you-colors -wal` and all the files are updated with the latest colors, can you share the output of that command please

Do I need to be using a specific fork of Pywal? I'm using python-pywal16 from the AUR. I just tried again by doing the following:

1. Delete ~/.cache/wal
2. Remove login script
3. Log out/back in
4. Change wallpaper
5. Run `kde-material-you-colors -wal`
6. Check ~/.cache/wal

It's still only generating the sequences file and none of the others. I have not changed anything with any of the templates and when I run pywal manually, it works perfectly fine. Here's that output you requested.

```
~
$ kde-material-you-colors -wal
[D] utils: kill_existing: Found previous process in PID file: '9753' killing...
[D] utils: kill_existing: Process not found, probably ended by someone else
[I] main: main: ###### STARTED NEW SESSION ######
[D] main: main: Installed in /usr/lib/python3.12/site-packages/kde_material_you_colors
[D] config: eval_conf: Config "iconslight": empty, using fallback: None
[D] config: eval_conf: Config "on_change_hook": empty, using fallback: None
[D] config: eval_conf: Config "color": empty, using fallback: None
[D] config: eval_conf: Config "custom_colors_list": empty, using fallback: None
[D] config: eval_conf: Config "darker_window_list": empty, using fallback: None
[D] config: eval_conf: Config "qdbus_executable": empty, using fallback: None
[D] main: main: {'light': None, 'file': None, 'monitor': 0, 'ncolor': 0, 'iconslight': None, 'iconsdark': 'breeze-dark', 'pywal': True, 'pywal_light': None, 'light_blend_multiplier': 1, 'dark_blend_multiplier': 1, 'on_change_hook': None, 'sierra_breeze_buttons_color': False, 'disable_konsole': False, 'titlebar_opacity': 100, 'titlebar_opacity_dark': 100, 'toolbar_opacity': 100, 'toolbar_opacity_dark': 100, 'konsole_opacity': 100, 'konsole_opacity_dark': 50, 'color': None, 'klassy_windeco_outline': False, 'custom_colors_list': None, 'darker_window_list': None, 'use_startup_delay': False, 'startup_delay': 0, 'plasma_follows_scheme': True, 'pywal_follows_scheme': True, 'main_loop_delay': 1.0, 'screenshot_delay': 900.0, 'once_after_change': False, 'pause_mode': False, 'screenshot_only_mode': False, 'scheme_variant': 6, 'chroma_multiplier': 1.0, 'tone_multiplier': 1.0, 'qdbus_executable': None}
[I] plasma_utils: get_initial_mode: Using theme from stored name
[I] main: main: Wallpaper: org.kde.image (image): /home/ego/Wallpapers/archgalaxy.jpg
[I] m3_scheme_utils: get_color_schemes: Best colors: 0:#1c1d34 1:#aa421f 2:#6b5c7d 3:#822657 4:#819cc4 5:#70636e 6:#bd864c
[I] m3_scheme_utils: get_color_schemes: Using seed: 0:#1c1d34
[I] plasma_utils: apply_color_schemes: Successfully applied the color scheme MaterialYouDark to your current Plasma session
[I] plasma_utils: set_icons: Icon theme changed to breeze-dark: org.kde.plasma.changeicons: Icon theme is already used
[I] kwin_utils: klassy_update_decoration_color_cache: Updating Klassy decoration color cache
[I] konsole_utils: get_default_profile: Found default profile 'Default.profile'
[D] konsole_utils: reload_profile: Konsole services (windows) running (1):
[D] konsole_utils: reload_profile: org.kde.konsole-11249 (1 sessions)
[I] pywal_utils: apply_schemes: Setting pywal colors...
[D] pywal_sequences_timeout: send: Sending sequences to /dev/pts/0
[I] pywal_sequences_timeout: send: Set terminal colors.
[I] pywal_utils: apply_schemes: Failed setting pywal colors:'checksum'
[I] kwin_utils: reload: Reloading KWin
 #12131c  #ee8f74  #f887bc  #d2a986  #a9affd  #a8b9d5  #d2bee8  #e6d2e3 
 #b8afcb  #f19e87  #fb97c5  #d8b496  #b4bafd  #b3c1db  #d8c6ec  #e9d8e6 
 #a099b3  #a36354  #ab5d85  #907560  #7479b1  #737f96  #9083a4  #9e91a0 
^CTraceback (most recent call last):
  File "/sbin/kde-material-you-colors", line 5, in <module>
    from kde_material_you_colors.main import main
  File "/usr/lib/python3.12/site-packages/kde_material_you_colors/main.py", line 507, in <module>
    main()
  File "/usr/lib/python3.12/site-packages/kde_material_you_colors/main.py", line 503, in main
    time.sleep(config.read("main_loop_delay"))
KeyboardInterrupt
```

**Comment by luisbocanegra** [comment]
> Do I need to be using a specific fork of Pywal?

No, only the original [python-pywal from extra repository](https://archlinux.org/packages/extra/any/python-pywal/) as listed in the https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=kde-material-you-colors#n8 is guaranteed to work.

From your log this seems to be the cause

```
pywal_utils: apply_schemes: Failed setting pywal colors:'checksum'
```

Switching back to python-pywal will make it work.

I am aware the original is no longer maintained so we will move over to [pywal16](https://github.com/eylles/pywal16) see https://github.com/luisbocanegra/kde-material-you-colors/issues/231

**Comment by areyoufeelingitnowmrkrebs** [comment]
So pywal16 isn't supported yet but the plan is to officially use that for material you?

**Comment by luisbocanegra** [comment]
Yes, just for clarity:

kde-material-you-colors takes colors from https://github.com/T-Dynamos/materialyoucolor-python and passes them to pywal which then generates all the cache files (simplified). In this case something changed in how pywal16 is doing this so we need to make it compatible again   but since the original pywal is now archived we will migrate to the pywal16 fork

**Comment by areyoufeelingitnowmrkrebs** [comment]
Okay got it, out of curiosity when is that forecast to happen? I'm probably just going to stick with pywal16 and wait for the transition so that I can still do GTK theming.

**Comment by luisbocanegra** [comment]
Been busy with other stuff lately but will try to do it this weekend.

Thanks for your patience.
