### ISSUE TITLE
No module named 'materialyoucolor' after upgrading to Python 3.13

### ISSUE THREAD

**Issue by Stabilizer1071** [luisbocanegra/kde-material-you-colors#240]
After upgrading to Python 3.13 today (Arch Linux, Core-Testing Repo), kde-material-you-colors is not functioning and gives following output:

```
Traceback (most recent call last): 
  File "/usr/bin/kde-material-you-colors", line 5, in <module>
    from kde_material_you_colors.main import main
  File "/usr/lib/python3.13/site-packages/kde_material_you_colors/main.py", line 507, in <module>
    main()
    ~~~~^^
  File "/usr/lib/python3.13/site-packages/kde_material_you_colors/main.py", line 354, in main
    from .config import Configs
  File "/usr/lib/python3.13/site-packages/kde_material_you_colors/config.py", line 4, in <module>
    from kde_material_you_colors.utils import color_utils
  File "/usr/lib/python3.13/site-packages/kde_material_you_colors/utils/color_utils.py", line 5, in <module>
    from materialyoucolor.blend import Blend
ModuleNotFoundError: No module named 'materialyoucolor'
```

The kde-material-you-colors is installed from AUR.

**Comment by luisbocanegra** [comment]
Looks like you need to rebuild your python packages https://github.com/luisbocanegra/kde-material-you-colors/issues/139

**Comment by Stabilizer1071** [comment]
Rebuild the `python-materialyoucolor-git` package solves the problem
Tried rebuilding `kde-material-you-colors` before which didn't work and totally forgot the `python-materialyoucolor-git` 😂
Thanks for your help!
