### ISSUE TITLE
Base command fails with `ModuleNotFoundError: No module named 'utils'`

### ISSUE THREAD

**Issue by boehs** [luisbocanegra/kde-material-you-colors#88]
**Describe the bug**

Base command fails with `ModuleNotFoundError: No module named 'utils'`

**To Reproduce**

```
➜  ~ yay kde-material-you-colors --rebuild
...
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting kde-material-you-colors-1.1.0.zip with bsdtar
==> Sources are ready.
kde-material-you-colors-1.1.0-1: parsing pkg list...
==> Making package: kde-material-you-colors 1.1.0-1 (Thu 15 Sep 2022 09:34:16 PM EDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting build()...
Listing '*.py'...
Can't list '*.py'
....
➜  ~ kde-material-you-colors           
Traceback (most recent call last):
  File "/usr/bin/kde-material-you-colors", line 4, in <module>
    import utils
ModuleNotFoundError: No module named 'utils'
```

**Expected behavior**

Command runs

**Desktop (please complete the following information):**
 - Arch Linux
 - 5.24.4

**Comment by luisbocanegra** [comment]
Oh, I've pushed an outdated PKGBUILD to the AUR I'll fix it in a moment, thanks for reporting.

**Comment by luisbocanegra** [comment]
Done

**Comment by boehs** [comment]
Now I'm hitting
```
➜  ~ kde-material-you-colors 
Traceback (most recent call last):
  File "/usr/bin/kde-material-you-colors", line 77, in <module>
    config = utils.Configs(args)
  File "/usr/lib/kde-material-you-colors/utils.py", line 246, in __init__
    elif c_pywal == None:
UnboundLocalError: local variable 'c_pywal' referenced before assignment
```

**Comment by luisbocanegra** [comment]
Should be fixed now, can you update and try again, please?

**Comment by boehs** [comment]
Thank you so much!
